### ISSUE TITLE
can you tell me why its not working in my case

### ISSUE THREAD

**Issue by Dipendra6377** [AleksandrRiabov/cryptoverse#1]
actually its showing useGetCryptoQuery is not a function

**Comment by Dipendra6377** [comment]
react-refresh-runtime.development.js:315 Uncaught TypeError: (0 , _sevices_cryptoApi__WEBPACK_IMPORTED_MODULE_2__.useGetCryptoQuery) is not a function

**Comment by AleksandrRiabov** [comment]
Hi, thanks for contacting me.

I've just tried to run it on my PC, and it still works without errors. ( Except for the fact that news  API does not work. If the news API is not going to be fixed anytime soon will have to look for another one. )

Regarding the error you get, I got a feeling that the conflict of dependencies versions caused it.  Can you try to delete the node_modules folder and run `npm i --legacy-peer-deps` that should install the correct versions of all dependencies. 

Another option is to clone the project again into the new directory and use the same `npm i --legacy-peer-deps` when installing dependencies. 

Please let me know if that did not help.

**Comment by Dipendra6377** [comment]
ok thanks for replying
